### ISSUE TITLE
fails for simple svgs

### ISSUE THREAD

**Issue by matkoniecz** [Amirh24/SVGAppender#3]
I tried to use

```
from svgimgutils import SVGImgUtils

base_template = SVGImgUtils.fromfile('a.svg')
base_template.save('merged.svg')
```

to process

```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="800" height="403" viewBox="0 0 800 403" stroke-linecap="round" stroke-linejoin="round">
<g id="jubilat_buildings_merge_transform" fill="none" stroke="black" stroke-width="1">
<path d="M 253.8906 185.3339 338.0649" stroke-width="7"/>
</g>
</svg>
```

It resulted in 

```
mateusz@grisznak:~/Desktop/osm-to-real/3D_map_for_blind$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    base_template = SVGImgUtils.fromfile('a.svg')
  File "/home/mateusz/.local/lib/python3.5/site-packages/svgimgutils.py", line 115, in fromfile
    fig.adddata()
  File "/home/mateusz/.local/lib/python3.5/site-packages/svgimgutils.py", line 145, in adddata
    self.number_of_classes = cssutils.parseString(self.style_element.text).cssRules.length
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/__init__.py", line 189, in parseString
    return CSSParser().parseString(*a, **k)
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/parse.py", line 148, in parseString
    encodingOverride=encoding)
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/css/cssstylesheet.py", line 355, in _setCssTextWithEncodingOverride
    self.cssText = cssText
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/css/cssstylesheet.py", line 303, in _setCssText
    default=ruleset)
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/util.py", line 462, in _parse
    for token in fulltokenizer:
  File "/home/mateusz/.local/lib/python3.5/site-packages/cssutils/tokenize2.py", line 126, in tokenize
    match = matcher(text, pos)
TypeError: expected string or bytes-like object
```

**Comment by Amirh24** [comment]
Hi, This library is no longer maintained.
It's encouraged to submit PRs in order to fix any issue and improve it.

**Comment by MrTeferi** [comment]
> 

I may take a crack at this later, I would really love to get this tool working Python doesn't really have anything that can easily accomplish merging SVG's at the moment. I'm working on a Django site for HTML5 games where players earn clothes for their profile and we layer several clothes on top of each other, SVG's are probably the best option quality-wise for these Illustrator assets and being able to merge a players profile image together rather than rendering 10 files each time might be a decent performance increase!
